# specify programming language
language: node_js
node_js: 10.18.1
cache: npm

branches:
  only:
    - master

# installation phase
install:
  - npm i

# tasks phase
script:
  - npm run test
  - npm run build

deploy:
  provider: surge
  skip_cleanup: true
  project: ./build/
  domain: todo.surge.sh
